import { Providers } from './providers';
import './global.scss';
import Navbar from '@/components/Navbar';
import { ClerkProvider } from '@clerk/nextjs';

export const metadata = {
  title: 'Welcome to tournament-io-next',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider
      appearance={{
        elements: {
          footer: 'hidden',
        },
      }}
    >
      <html lang="en" className="dark">
        <body>
          <Providers>
            <Navbar />
            {children}
          </Providers>
        </body>
      </html>
    </ClerkProvider>
  );
}
